// Sahyog - Central Constants & Seed Configurations
import { ServiceCategory, Service, UserRole } from "@/types";

export const APP_NAME = "Sahyog";
export const APP_TAGLINE = "Connecting Cooperative Skills with Everyday Needs";
export const APP_DESCRIPTION =
  "A cooperative-owned digital service marketplace connecting skilled workers registered with Labour Cooperative Federations and Societies with households, businesses, institutions, and communities.";

export const MONOCHROME_THEME = {
  primary: "#111111",
  primaryHover: "#262626",
  background: "#FFFFFF",
  secondaryBg: "#F8F8F8",
  cardSurface: "#F3F3F3",
  border: "#E5E5E5",
  mutedBorder: "#D4D4D4",
  primaryText: "#171717",
  secondaryText: "#525252",
  mutedText: "#737373",
  disabledText: "#A3A3A3",
  inverseText: "#FFFFFF",
};

export const FUNCTIONAL_COLORS = {
  success: "#16A34A",
  warning: "#D97706",
  error: "#DC2626",
  info: "#2563EB",
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "cat_electrical",
    name: "Electrical Services",
    nameHi: "विद्युत सेवाएं",
    slug: "electrical",
    description: "Wiring, switchboard repairs, appliance installation, MCB tripping and power backup setup.",
    descriptionHi: "वायरिंग, स्विचबोर्ड मरम्मत, उपकरण स्थापना और विद्युत सुरक्षा कार्य।",
    iconName: "Zap",
    isActive: true,
    servicesCount: 3,
  },
  {
    id: "cat_plumbing",
    name: "Plumbing Services",
    nameHi: "प्लंबिंग सेवाएं",
    slug: "plumbing",
    description: "Pipe leak fixes, tap & shower fitting, water tank cleaning, drainage unclogging and motor setup.",
    descriptionHi: "पाइप लीकेज, नल व शॉवर फिटिंग, पानी की टंकी की सफाई और मोटर मरम्मत।",
    iconName: "Wrench",
    isActive: true,
    servicesCount: 3,
  },
  {
    id: "cat_carpentry",
    name: "Carpentry & Furniture",
    nameHi: "बढ़ईगीरी व फर्नीचर",
    slug: "carpentry",
    description: "Furniture assembly, door lock fixing, cabinet repairs, polishing and custom woodwork.",
    descriptionHi: "फर्नीचर निर्माण, दरवाजे के ताले, अलमारी मरम्मत और लकड़ी का कार्य।",
    iconName: "Hammer",
    isActive: true,
    servicesCount: 2,
  },
  {
    id: "cat_painting",
    name: "Painting & Whitewash",
    nameHi: "पेंटिंग व पुताई",
    slug: "painting",
    description: "Interior/exterior wall painting, waterproofing, damp proofing, and texture work.",
    descriptionHi: "आंतरिक एवं बाहरी दीवार पेंटिंग, वॉटरप्रूफिंग और सफेदी कार्य।",
    iconName: "Paintbrush",
    isActive: true,
    servicesCount: 2,
  },
  {
    id: "cat_cleaning",
    name: "Deep Cleaning & Sanitation",
    nameHi: "सफाई एवं स्वच्छता",
    slug: "cleaning",
    description: "Home deep cleaning, kitchen degreasing, bathroom disinfection and sofa shampooing.",
    descriptionHi: "घर की डीप क्लीनिंग, रसोई व बाथरूम की स्वच्छता और सोफा सफाई।",
    iconName: "Sparkles",
    isActive: true,
    servicesCount: 2,
  },
  {
    id: "cat_domestic",
    name: "Domestic & Household Help",
    nameHi: "घरेलू सहायता",
    slug: "domestic-help",
    description: "Verified cooperative domestic helpers, kitchen prep assistants and housekeeping support.",
    descriptionHi: "सत्यापित सहकारी घरेलू सहायक, रसोई सहायक और गृह व्यवस्था।",
    iconName: "Home",
    isActive: true,
    servicesCount: 2,
  },
  {
    id: "cat_caregiving",
    name: "Elderly & Patient Care",
    nameHi: "बुजुर्ग व मरीज देखभाल",
    slug: "caregiving",
    description: "Trained and cooperative-verified caregivers, mobility assistance, medication routine helpers.",
    descriptionHi: "प्रशिक्षित और सहकारी-सत्यापित देखभालकर्ता, सहायता और देखभाल।",
    iconName: "HeartHandshake",
    isActive: true,
    servicesCount: 2,
  },
  {
    id: "cat_gardening",
    name: "Gardening & Landscaping",
    nameHi: "बागवानी व पौध संरक्षण",
    slug: "gardening",
    description: "Lawn mowing, plant pruning, organic fertilization, pest control and terrace garden setup.",
    descriptionHi: "लॉन कटाई, पौधों की छंटाई, जैविक खाद और छत पर बागवानी सेटअप।",
    iconName: "Flower2",
    isActive: true,
    servicesCount: 2,
  },
  {
    id: "cat_driving",
    name: "Driver on Demand",
    nameHi: "ड्राइवर सेवा",
    slug: "driving",
    description: "Hourly, daily and outstation verified cooperative commercial and personal drivers.",
    descriptionHi: "सत्यापित सहकारी व्यक्तिगत एवं व्यावसायिक ड्राइवर सेवा।",
    iconName: "Car",
    isActive: true,
    servicesCount: 2,
  },
  {
    id: "cat_technical",
    name: "Technical & Appliance Repair",
    nameHi: "तकनीकी उपकरण मरम्मत",
    slug: "technical",
    description: "AC servicing, washing machine, refrigerator, geyser, and microwave repairs.",
    descriptionHi: "एसी सर्विसिंग, वाशिंग मशीन, फ्रिज और गीजर मरम्मत सेवा।",
    iconName: "Cpu",
    isActive: true,
    servicesCount: 2,
  },
];

export const SERVICES: Service[] = [
  {
    id: "srv_plumb_emergency",
    categoryId: "cat_plumbing",
    categoryName: "Plumbing Services",
    name: "Emergency Leak & Pipe Burst Repair",
    nameHi: "आपातकालीन पाइप लीकेज मरम्मत",
    description: "Immediate response for severe water leaks, burst pipes, overflowing overhead tanks, or sudden motor failures.",
    descriptionHi: "गंभीर पानी रिसाव, फटे पाइप और मोटर खराबी के लिए तत्काल सेवा।",
    basePrice: 450,
    estimatedDurationMins: 45,
    isEmergencyEligible: true,
  },
  {
    id: "srv_plumb_standard",
    categoryId: "cat_plumbing",
    categoryName: "Plumbing Services",
    name: "Tap, Shower & Sanitary Fitting",
    nameHi: "नल, शॉवर एवं सेनेटरी फिटिंग",
    description: "Installation and repair of bathroom faucets, shower heads, flush valves, and washbasin siphons.",
    descriptionHi: "बाथरूम नल, शॉवर और फ्लश वॉल्व की फिटिंग व मरम्मत।",
    basePrice: 299,
    estimatedDurationMins: 60,
    isEmergencyEligible: false,
  },
  {
    id: "srv_plumb_drainage",
    categoryId: "cat_plumbing",
    categoryName: "Plumbing Services",
    name: "Drainage & Sewer Line Unclogging",
    nameHi: "नाली एवं ड्रेनेज सफाई",
    description: "Heavy-duty unblocking for kitchen sinks, bathroom drains, floor traps and sewer lines.",
    descriptionHi: "रसोई सिंक, बाथरूम ड्रेन और सीवर लाइन की सफाई।",
    basePrice: 499,
    estimatedDurationMins: 90,
    isEmergencyEligible: true,
  },
  {
    id: "srv_elec_emergency",
    categoryId: "cat_electrical",
    categoryName: "Electrical Services",
    name: "Emergency Power & Short Circuit Fix",
    nameHi: "आपातकालीन शॉर्ट सर्किट व बिजली मरम्मत",
    description: "Urgent troubleshooting for total power outage, burning smell from wires, sparks, or recurring MCB trips.",
    descriptionHi: "बिजली गुल, शॉर्ट सर्किट, स्पार्किंग या एमसीबी ट्रिपिंग का त्वरित समाधान।",
    basePrice: 499,
    estimatedDurationMins: 45,
    isEmergencyEligible: true,
  },
  {
    id: "srv_elec_switchboard",
    categoryId: "cat_electrical",
    categoryName: "Electrical Services",
    name: "Switchboard & Socket Installation",
    nameHi: "स्विचबोर्ड एवं सॉकेट फिटिंग",
    description: "Repair, replacement and modern modular switchboard wiring with earthing checks.",
    descriptionHi: "मॉड्यूलर स्विचबोर्ड, सॉकेट की मरम्मत व अर्थिंग जांच।",
    basePrice: 249,
    estimatedDurationMins: 45,
    isEmergencyEligible: false,
  },
  {
    id: "srv_elec_fan_appliance",
    categoryId: "cat_electrical",
    categoryName: "Electrical Services",
    name: "Ceiling Fan & Light Fixtures Setup",
    nameHi: "पंखे एवं लाइट फिटिंग",
    description: "Installation and repair of decorative lights, LED panels, ceiling fans, and exhaust fans.",
    descriptionHi: "सीलिंग फैन, एलईडी पैनल और लाइट फिक्स्चर की फिटिंग।",
    basePrice: 199,
    estimatedDurationMins: 40,
    isEmergencyEligible: false,
  },
  {
    id: "srv_carp_repair",
    categoryId: "cat_carpentry",
    categoryName: "Carpentry & Furniture",
    name: "Door, Window & Lock Repair",
    nameHi: "दरवाजे, खिड़की व लॉक मरम्मत",
    description: "Hinges alignment, door latch, lock replacement, sliding track fixes, and mesh replacement.",
    descriptionHi: "दरवाजे के कब्जे, ताले की मरम्मत और जाली फिटिंग।",
    basePrice: 349,
    estimatedDurationMins: 60,
    isEmergencyEligible: true,
  },
  {
    id: "srv_carp_assembly",
    categoryId: "cat_carpentry",
    categoryName: "Carpentry & Furniture",
    name: "Furniture Assembly & Woodwork",
    nameHi: "फर्नीचर असेंबली व बढ़ईगीरी",
    description: "Assembly of flat-pack beds, wardrobes, study tables, shelf mounting and wood polishing.",
    descriptionHi: "बेड, अलमारी, टेबल असेंबली और पॉलिशिंग कार्य।",
    basePrice: 599,
    estimatedDurationMins: 120,
    isEmergencyEligible: false,
  },
  {
    id: "srv_clean_deep",
    categoryId: "cat_cleaning",
    categoryName: "Deep Cleaning & Sanitation",
    name: "Full Home Deep Sanitization",
    nameHi: "सम्पूर्ण घर की डीप क्लीनिंग",
    description: "Intensive scrubbing, vacuuming, disinfection of all rooms, balconies, fans, and glass panes.",
    descriptionHi: "कमरों, बालकनी, पंखों और खिड़कियों की गहन सफाई।",
    basePrice: 1499,
    estimatedDurationMins: 180,
    isEmergencyEligible: false,
  },
  {
    id: "srv_clean_kitchen",
    categoryId: "cat_cleaning",
    categoryName: "Deep Cleaning & Sanitation",
    name: "Kitchen & Chimney Degreasing",
    nameHi: "रसोई एवं चिमनी डीग्रीजिंग",
    description: "High-temperature steam removal of oil stains, chimney mesh washing, countertop sanitization.",
    descriptionHi: "तेल के दाग हटाना, चिमनी की जाली धोना और स्लैब की सफाई।",
    basePrice: 799,
    estimatedDurationMins: 90,
    isEmergencyEligible: false,
  },
  {
    id: "srv_paint_touchup",
    categoryId: "cat_painting",
    categoryName: "Painting & Whitewash",
    name: "Wall Touchup & Damp Repair",
    nameHi: "दीवार पुट्टी व सीलन मरम्मत",
    description: "Seepage treatment, putty leveling, primer coat and matching paint touchup for damaged areas.",
    descriptionHi: "सीलन उपचार, पुट्टी भराव और दीवार टच-अप पेंटिंग।",
    basePrice: 899,
    estimatedDurationMins: 120,
    isEmergencyEligible: false,
  },
  {
    id: "srv_care_daily",
    categoryId: "cat_caregiving",
    categoryName: "Elderly & Patient Care",
    name: "Elderly Assistance & Daily Care (4-Hour)",
    nameHi: "बुजुर्ग सहायता एवं दैनिक देखभाल",
    description: "Assistance with walking, feeding, vital monitoring, conversation, and companionship by certified staff.",
    descriptionHi: "चलने-फिरने, भोजन, स्वास्थ्य निगरानी और देखभाल में सहायता।",
    basePrice: 650,
    estimatedDurationMins: 240,
    isEmergencyEligible: true,
  },
  {
    id: "srv_tech_ac",
    categoryId: "cat_technical",
    categoryName: "Technical & Appliance Repair",
    name: "AC Jet Servicing & Gas Leak Check",
    nameHi: "एसी जेट सर्विसिंग व गैस जांच",
    description: "High-pressure pump water cleaning of indoor/outdoor unit coils, filter cleansing, and cooling check.",
    descriptionHi: "हाई-प्रेशर वाटर कॉइल क्लीनिंग, फिल्टर धुलाई और कूलिंग टेस्ट।",
    basePrice: 549,
    estimatedDurationMins: 60,
    isEmergencyEligible: false,
  },
];

export const DEMO_USERS = [
  {
    id: "cust_demo_1",
    email: "customer.demo@example.com",
    fullName: "Aarav Sharma",
    phone: "+91 98765 43210",
    role: "CUSTOMER" as UserRole,
    address: "B-402, Green Valley Apartments, Sector 62",
    city: "Noida",
    state: "Uttar Pradesh",
    postalCode: "201301",
    lat: 28.628,
    lng: 77.3649,
  },
  {
    id: "worker_demo_1",
    email: "worker.demo@example.com",
    fullName: "Ramesh Kumar Verma",
    phone: "+91 98111 22334",
    role: "WORKER" as UserRole,
    address: "Shop 12, Cooperative Nagar, Sector 59",
    city: "Noida",
    state: "Uttar Pradesh",
    postalCode: "201301",
    lat: 28.625,
    lng: 77.368,
  },
  {
    id: "admin_demo_1",
    email: "admin.demo@example.com",
    fullName: "Sunita Deshmukh",
    phone: "+91 98222 33445",
    role: "SOCIETY_ADMIN" as UserRole,
    address: "Labour Cooperative Bhawan, Sector 62",
    city: "Noida",
    state: "Uttar Pradesh",
    postalCode: "201301",
    lat: 28.629,
    lng: 77.362,
  },
  {
    id: "fed_demo_1",
    email: "federation.demo@example.com",
    fullName: "Dr. Rajeshwar Patil",
    phone: "+91 98333 44556",
    role: "FEDERATION_ADMIN" as UserRole,
    address: "National Cooperative Union Complex, Siri Fort",
    city: "New Delhi",
    state: "Delhi",
    postalCode: "110049",
    lat: 28.552,
    lng: 77.218,
  },
];

export const COOPERATIVE_SOCIETIES = [
  {
    id: "coop_noida_1",
    federationId: "fed_delhi_ncr",
    name: "Noida Shramik Utthan Labour Cooperative Society Ltd.",
    registrationNo: "UP/COOP/2018/8892",
    district: "Gautam Buddha Nagar",
    address: "Plot 18, Block C, Sector 62, Noida, UP 201301",
    contactPerson: "Sunita Deshmukh",
    phone: "+91 98222 33445",
    email: "admin.noida@sahyogcoop.in",
    isActive: true,
    workersCount: 6,
  },
  {
    id: "coop_ghaziabad_1",
    federationId: "fed_delhi_ncr",
    name: "Ghaziabad Kaushal Vikas Labour Cooperative Society Ltd.",
    registrationNo: "UP/COOP/2020/4119",
    district: "Ghaziabad",
    address: "B-2, Industrial Area, Raj Nagar, Ghaziabad, UP 201002",
    contactPerson: "Mahesh Chandra",
    phone: "+91 98444 55667",
    email: "admin.gzb@sahyogcoop.in",
    isActive: true,
    workersCount: 4,
  },
];

export const FEDERATION = {
  id: "fed_delhi_ncr",
  name: "National Capital Region Labour Cooperative Federation",
  registrationNo: "FED/NCR/2015/0014",
  state: "Delhi & NCR",
  contactEmail: "contact@ncrfederation.org",
  phone: "+91 11 2649 8871",
  societiesCount: 2,
  workersCount: 10,
};

export const COMMISSION_RATES = {
  platformFeePercent: 5,   // 5% Platform Maintenance
  cooperativeFeePercent: 7, // 7% Cooperative Welfare & Training Fund
  workerSharePercent: 88,  // 88% Direct to Cooperative Worker
};